name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.
  - pandas=1.2.3
  - pip:
      - wandb==0.10.31
      # - pip install protobuf==3.20.0 this is needed otherwise will fail
